# Generated by Django 3.2.8 on 2021-10-29 10:22

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('types', models.CharField(choices=[('pickleball', 'Pickleball'), ('tennis', 'Tennis'), ('badminton', 'Badminton')], default='tennis', max_length=50)),
                ('buy_membership', models.BooleanField(null=True)),
                ('num_courts', models.IntegerField()),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Court phone number', max_length=31)),
                ('info', models.TextField()),
                ('rating', models.FloatField()),
                ('website', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('cost', models.CharField(choices=[('paid', 'Paid'), ('free', 'Free'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('need_membership', models.BooleanField(null=True)),
                ('has_lighting', models.BooleanField(null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
