# Generated by Django 3.2.8 on 2021-10-29 14:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_auto_20211029_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), null=True, size=None),
        ),
    ]
