# Generated by Django 3.2.8 on 2021-10-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        ('courts', '0004_alter_court_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='images',
        ),
        migrations.AddField(
            model_name='court',
            name='images',
            field=models.ManyToManyField(to='photos.Photo'),
        ),
    ]
